version: 1.0.{build}

branches:

  only:

  - master

image: Visual Studio 2017

configuration: Release

clone_depth: 2

before_build:

- cmd: nuget restore

build:

  project: ./Sources

  verbosity: minimal