version: 1.0.{build}

branches:

  only:

  - master

image: Visual Studio 2017

configuration: Release

clone_depth: 2

build_script:

- cmd: msbuild Sources/Habbi.Utils.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"